// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.4
// source: checkpb/check.proto

package checkpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checklist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order    int32  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Channel  string `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Code     string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Category string `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Item     string `protobuf:"bytes,6,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *Checklist) Reset() {
	*x = Checklist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Checklist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checklist) ProtoMessage() {}

func (x *Checklist) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checklist.ProtoReflect.Descriptor instead.
func (*Checklist) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{0}
}

func (x *Checklist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checklist) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Checklist) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Checklist) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Checklist) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Checklist) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type CreateChecklistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checklist *Checklist `protobuf:"bytes,1,opt,name=checklist,proto3" json:"checklist,omitempty"`
}

func (x *CreateChecklistRequest) Reset() {
	*x = CreateChecklistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChecklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChecklistRequest) ProtoMessage() {}

func (x *CreateChecklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChecklistRequest.ProtoReflect.Descriptor instead.
func (*CreateChecklistRequest) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChecklistRequest) GetChecklist() *Checklist {
	if x != nil {
		return x.Checklist
	}
	return nil
}

type CreateChecklistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Checklist `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateChecklistResponse) Reset() {
	*x = CreateChecklistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChecklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChecklistResponse) ProtoMessage() {}

func (x *CreateChecklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChecklistResponse.ProtoReflect.Descriptor instead.
func (*CreateChecklistResponse) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChecklistResponse) GetResult() *Checklist {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReadChecklistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadChecklistRequest) Reset() {
	*x = ReadChecklistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadChecklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChecklistRequest) ProtoMessage() {}

func (x *ReadChecklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChecklistRequest.ProtoReflect.Descriptor instead.
func (*ReadChecklistRequest) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{3}
}

func (x *ReadChecklistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadChecklistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Checklist `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ReadChecklistResponse) Reset() {
	*x = ReadChecklistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadChecklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChecklistResponse) ProtoMessage() {}

func (x *ReadChecklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChecklistResponse.ProtoReflect.Descriptor instead.
func (*ReadChecklistResponse) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{4}
}

func (x *ReadChecklistResponse) GetResult() *Checklist {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReadChecklistQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *Checklist `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *ReadChecklistQueryRequest) Reset() {
	*x = ReadChecklistQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadChecklistQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChecklistQueryRequest) ProtoMessage() {}

func (x *ReadChecklistQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChecklistQueryRequest.ProtoReflect.Descriptor instead.
func (*ReadChecklistQueryRequest) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{5}
}

func (x *ReadChecklistQueryRequest) GetQuery() *Checklist {
	if x != nil {
		return x.Query
	}
	return nil
}

type UpdateChecklistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checklist *Checklist `protobuf:"bytes,1,opt,name=checklist,proto3" json:"checklist,omitempty"`
}

func (x *UpdateChecklistRequest) Reset() {
	*x = UpdateChecklistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChecklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChecklistRequest) ProtoMessage() {}

func (x *UpdateChecklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChecklistRequest.ProtoReflect.Descriptor instead.
func (*UpdateChecklistRequest) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateChecklistRequest) GetChecklist() *Checklist {
	if x != nil {
		return x.Checklist
	}
	return nil
}

type UpdateChecklistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Checklist `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UpdateChecklistResponse) Reset() {
	*x = UpdateChecklistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChecklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChecklistResponse) ProtoMessage() {}

func (x *UpdateChecklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChecklistResponse.ProtoReflect.Descriptor instead.
func (*UpdateChecklistResponse) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateChecklistResponse) GetResult() *Checklist {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteChecklistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteChecklistRequest) Reset() {
	*x = DeleteChecklistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChecklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChecklistRequest) ProtoMessage() {}

func (x *DeleteChecklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChecklistRequest.ProtoReflect.Descriptor instead.
func (*DeleteChecklistRequest) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChecklistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChecklistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeleteChecklistResponse) Reset() {
	*x = DeleteChecklistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChecklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChecklistResponse) ProtoMessage() {}

func (x *DeleteChecklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChecklistResponse.ProtoReflect.Descriptor instead.
func (*DeleteChecklistResponse) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteChecklistResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type ListChecklistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListChecklistRequest) Reset() {
	*x = ListChecklistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChecklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChecklistRequest) ProtoMessage() {}

func (x *ListChecklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChecklistRequest.ProtoReflect.Descriptor instead.
func (*ListChecklistRequest) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{10}
}

type ListChecklistResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Checklist `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ListChecklistResponse) Reset() {
	*x = ListChecklistResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListChecklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChecklistResponse) ProtoMessage() {}

func (x *ListChecklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChecklistResponse.ProtoReflect.Descriptor instead.
func (*ListChecklistResponse) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{11}
}

func (x *ListChecklistResponse) GetResult() *Checklist {
	if x != nil {
		return x.Result
	}
	return nil
}

type StringMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkpb_check_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_checkpb_check_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_checkpb_check_proto_rawDescGZIP(), []int{12}
}

func (x *StringMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_checkpb_check_proto protoreflect.FileDescriptor

var file_checkpb_check_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f,
	0x01, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x22, 0x4c, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x47,
	0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x64, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x45, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x47, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x4c, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x47, 0x0a,
	0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x31, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x25, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xf8, 0x05, 0x0a, 0x10, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57,
	0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x18, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x18, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f,
	0x65, 0x63, 0x68, 0x6f, 0x3a, 0x01, 0x2a, 0x12, 0x5a, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1f, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a,
	0x14, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x79,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x24, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x5a, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x73, 0x74, 0x12,
	0x21, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x43,
	0x68, 0x65, 0x63, 0x6c, 0x6b, 0x69, 0x73, 0x74, 0x73, 0x12, 0x1f, 0x2e, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x62, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x6c, 0x6b, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_checkpb_check_proto_rawDescOnce sync.Once
	file_checkpb_check_proto_rawDescData = file_checkpb_check_proto_rawDesc
)

func file_checkpb_check_proto_rawDescGZIP() []byte {
	file_checkpb_check_proto_rawDescOnce.Do(func() {
		file_checkpb_check_proto_rawDescData = protoimpl.X.CompressGZIP(file_checkpb_check_proto_rawDescData)
	})
	return file_checkpb_check_proto_rawDescData
}

var file_checkpb_check_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_checkpb_check_proto_goTypes = []interface{}{
	(*Checklist)(nil),                 // 0: checklist.Checklist
	(*CreateChecklistRequest)(nil),    // 1: checklist.CreateChecklistRequest
	(*CreateChecklistResponse)(nil),   // 2: checklist.CreateChecklistResponse
	(*ReadChecklistRequest)(nil),      // 3: checklist.ReadChecklistRequest
	(*ReadChecklistResponse)(nil),     // 4: checklist.ReadChecklistResponse
	(*ReadChecklistQueryRequest)(nil), // 5: checklist.ReadChecklistQueryRequest
	(*UpdateChecklistRequest)(nil),    // 6: checklist.UpdateChecklistRequest
	(*UpdateChecklistResponse)(nil),   // 7: checklist.UpdateChecklistResponse
	(*DeleteChecklistRequest)(nil),    // 8: checklist.DeleteChecklistRequest
	(*DeleteChecklistResponse)(nil),   // 9: checklist.DeleteChecklistResponse
	(*ListChecklistRequest)(nil),      // 10: checklist.ListChecklistRequest
	(*ListChecklistResponse)(nil),     // 11: checklist.ListChecklistResponse
	(*StringMessage)(nil),             // 12: checklist.StringMessage
}
var file_checkpb_check_proto_depIdxs = []int32{
	0,  // 0: checklist.CreateChecklistRequest.checklist:type_name -> checklist.Checklist
	0,  // 1: checklist.CreateChecklistResponse.result:type_name -> checklist.Checklist
	0,  // 2: checklist.ReadChecklistResponse.result:type_name -> checklist.Checklist
	0,  // 3: checklist.ReadChecklistQueryRequest.query:type_name -> checklist.Checklist
	0,  // 4: checklist.UpdateChecklistRequest.checklist:type_name -> checklist.Checklist
	0,  // 5: checklist.UpdateChecklistResponse.result:type_name -> checklist.Checklist
	0,  // 6: checklist.ListChecklistResponse.result:type_name -> checklist.Checklist
	12, // 7: checklist.ChecklistService.Echo:input_type -> checklist.StringMessage
	1,  // 8: checklist.ChecklistService.CreateChecklist:input_type -> checklist.CreateChecklistRequest
	3,  // 9: checklist.ChecklistService.ReadChecklistByID:input_type -> checklist.ReadChecklistRequest
	5,  // 10: checklist.ChecklistService.ReadChecklistByQuery:input_type -> checklist.ReadChecklistQueryRequest
	6,  // 11: checklist.ChecklistService.UpdateChecklist:input_type -> checklist.UpdateChecklistRequest
	8,  // 12: checklist.ChecklistService.DeleteCheckist:input_type -> checklist.DeleteChecklistRequest
	10, // 13: checklist.ChecklistService.AllCheclkists:input_type -> checklist.ListChecklistRequest
	1,  // 14: checklist.ChecklistService.CreateBulkChecklist:input_type -> checklist.CreateChecklistRequest
	12, // 15: checklist.ChecklistService.Echo:output_type -> checklist.StringMessage
	2,  // 16: checklist.ChecklistService.CreateChecklist:output_type -> checklist.CreateChecklistResponse
	4,  // 17: checklist.ChecklistService.ReadChecklistByID:output_type -> checklist.ReadChecklistResponse
	4,  // 18: checklist.ChecklistService.ReadChecklistByQuery:output_type -> checklist.ReadChecklistResponse
	7,  // 19: checklist.ChecklistService.UpdateChecklist:output_type -> checklist.UpdateChecklistResponse
	9,  // 20: checklist.ChecklistService.DeleteCheckist:output_type -> checklist.DeleteChecklistResponse
	11, // 21: checklist.ChecklistService.AllCheclkists:output_type -> checklist.ListChecklistResponse
	2,  // 22: checklist.ChecklistService.CreateBulkChecklist:output_type -> checklist.CreateChecklistResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_checkpb_check_proto_init() }
func file_checkpb_check_proto_init() {
	if File_checkpb_check_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_checkpb_check_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Checklist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChecklistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChecklistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadChecklistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadChecklistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadChecklistQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChecklistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChecklistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChecklistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChecklistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChecklistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListChecklistResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkpb_check_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checkpb_check_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkpb_check_proto_goTypes,
		DependencyIndexes: file_checkpb_check_proto_depIdxs,
		MessageInfos:      file_checkpb_check_proto_msgTypes,
	}.Build()
	File_checkpb_check_proto = out.File
	file_checkpb_check_proto_rawDesc = nil
	file_checkpb_check_proto_goTypes = nil
	file_checkpb_check_proto_depIdxs = nil
}
